modLoader = "javafml"
loaderVersion = "[47,)"
issueTrackerURL = "https://github.com/UpperMoon0/Perfomant-Boom/issues"
license = "MIT"

[[mods]]
modId = "perfomant_boom"
version = "${version}"
displayName = "Perfomant Boom"
authors = "NsTut"
description = '''
Scheduled explosions and a reusable bounded terrain API.
'''

[[dependencies.perfomant_boom]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.perfomant_boom]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.perfomant_boom]]
modId = "architectury"
mandatory = true
versionRange = "[9.2.14,)"
ordering = "AFTER"
side = "BOTH"
