plugins { id 'java-library'; id 'maven-publish' }
repositories { mavenCentral() }
java { toolchain.languageVersion = JavaLanguageVersion.of(17); withSourcesJar() }
base { archivesName = 'perfomant_boom-core' }
dependencies { testImplementation 'org.junit.jupiter:junit-jupiter:5.9.2' }
test { useJUnitPlatform() }
publishing { publications { mavenJava(MavenPublication) { from components.java; artifactId = 'perfomant_boom-core' } } }
